<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Sentinel.Worker-3d760f75-892d-4385-82e5-abe40a56f6ad</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.28.3" />
    <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
    <PackageReference Include="Grpc.Tools" Version="2.67.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Sentinel.Infrastructure\Protos\sentinel.proto" GrpcServices="Client" Link="Protos\sentinel.proto" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sentinel.Domain\Sentinel.Domain.csproj" />
  </ItemGroup>
</Project>
